### ISSUE TITLE
ide chart : cannot working backend sts with sqlite

### ISSUE THREAD

**Issue by suminhong** [langflow-ai/langflow-helm-charts#21]
Hi, I'm simply trying to install this langflow-ide chart on my company's Kubernetes.

I used the value file below.
```yaml
langflow:
  backend:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 7860
    backendOnly: true
    numWorkers: 1
    image:
      tag: v1.1.1
    sqlite:
      enabled: true
      volume:
        size: "10Gi"
        existingStorageClassName: "gp3"
    env:
      - name: LANGFLOW_PORT
        value: "7860"
  
  frontend:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8080
    image:
      tag: v1.1.1
```
But the following error occurs.
```
                             │                                     │
                             │    618 │                            │
                             │    619 │   def connect(self, *cargs │
                             │    620 │   │   # inherits the docst │
                             │ ❱  621 │   │   return self.loaded_d │
                             │    622 │                            │
                             │    623 │   def create_connect_args( │
                             │    624 │   │   # inherits the docst │
                             ╰─────────────────────────────────────╯
                             OperationalError: unable to open
                             database file
                             The above exception was the direct
                             cause of the following exception:
                             ╭─ Traceback (most recent call last) ─╮
                             │ /app/.venv/lib/python3.12/site-pack │
                             │ ages/sqlalchemy/engine/default.py:6 │
                             │ 21 in connect                       │
                             │                                     │
                             │    618 │                            │
                             │    619 │   def connect(self, *cargs │
                             │    620 │   │   # inherits the docst │
                             │ ❱  621 │   │   return self.loaded_d │
                             │    622 │                            │
                             │    623 │   def create_connect_args( │
                             │    624 │   │   # inherits the docst │
                             ╰─────────────────────────────────────╯
                             OperationalError:
                             (sqlite3.OperationalError) unable to
                             open database file
                             (Background on this error at:
                             https://sqlalche.me/e/20/e3q8)
```
Can you tell me what the problem might be? frontend pod is fine.
