### ISSUE TITLE
How to configure PVC to store flows with psql db

### ISSUE THREAD

**Issue by exilehanharr** [langflow-ai/langflow-helm-charts#30]
Hi!

I've deployed langflow-ide with psql. If I deploy a new version of `backend` my projects is cleaned up. How can I use PVC to save my projects?

**Comment by Taffarel** [comment]
Hello,

You can add the volume for the stateful set using the following. Apply this as a patch that will override the default StatefulSet

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: langflow-service
spec:
  volumeClaimTemplates:
    - apiVersion: v1	
      kind: PersistentVolumeClaim	
      metadata:
        name: data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
```


Then over your values.yaml you will need to add the following:
```yaml
    volumeMounts:
      - name: data-volume
        mountPath: /app/flows
      - name: data-volume
        mountPath: /app/data
      - name: data-volume
        mountPath: /app/db
      - name: tmp
        mountPath: /tmp
        readOnly: false
```
