### ISSUE TITLE
MAX Upload file size

### ISSUE THREAD

**Issue by sweco-nlmdek** [langflow-ai/langflow-helm-charts#34]
Hi, i have langflow running on a azure kubernetes.
When testing i came across the following error when uploaden a 2.5mb large PDF file : 413 (Request Entity Too Large)

![Image](https://github.com/user-attachments/assets/39e86aa2-a49a-4ac4-9f55-4ee9c938624e)

So i have been trying to solve this, but no matter what i tried i aint working.

frontend is of type: LoadBalancer

i have added the following env variables, both in frontend and backend.

  - name: MAX_CONTENT_LENGTH
     value: "100000000"  # 100MB
  - name: MAX_UPLOAD_SIZE
    value: "100M"
  - name : LANGFLOW_MAX_FILE_SIZE_UPLOAD
     value: "100"

i have tried specifying like this in the frontend:
  nginx:
      client_max_body_size: "200M"

**Comment by Taffarel** [comment]
To solve this issue using the Helm chart, add this on the ingress.yaml file

```yaml
...
  rules:
    - host: myhost.local
      http:
        paths:
          - backend:
              service:
                name: langflow-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: langflow-service-backend
                port:
                  number: 7860
            path: /api
            pathType: Prefix
...
```

This will override the frontend call to request directly to the langflow-service-backend

https://github.com/langflow-ai/langflow/blob/main/docker/frontend/nginx.conf this is the nginx config file that causes the issue.
